#
# Module manifest for module 'Fabtools'
#
# Generated by: Ioana Bouariu
#
# Generated on: 05.11.2023
#

@{

    # Script module or binary module file associated with this manifest.
    # RootModule = ''

    # Version number of this module.
    ModuleVersion     = '0.6.1'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID              = '8bc9ba6c-218d-4a2a-ba89-66a492a1616c'

    # Author of this module
    Author            = 'Ioana Bouariu AKA Jojobit'

    # Company or vendor of this module
    CompanyName       = ''

    # Copyright statement for this module
    Copyright         = 'Ioana Bouariu'

    # Description of the functionality provided by this module
    Description       = 'A module to be able to do more with Microsoft Fabric.
    It lets you pause and resume Fabric capacities.
    Adds functionallity previously only available with the REST API as PowerShell functions.
    There are also functions to make it easier to monitor usage metrics and refreshes.
    It also adds Fabric-friendly aliases for PowerBI functions to make it easier to use the module.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules   = @('MicrosoftPowerBIMgmt')

    # Assemblies that must be loaded prior to importing this module
    #RequiredAssemblies = @('Az.Accounts', 'Az.Resources')

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules = 'Fabtools.psm1'

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        'Set-FabricWorkspaceToCapacity',
        'Get-AllFabricDatasetRefreshes',
        'Get-AllFabricCapacities',
        'Get-FabricAPIclusterURI',
        'Get-FabricCapacityRefreshables',
        'Get-FabricCapacityState',
        'Get-FabricCapacityTenantOverrides',
        'Get-FabricCapacityWorkload',
        'Get-FabricDatasetRefreshes',
        'Get-FabricTenantSettings',
        'Get-FabricUsagemetricsQuery',
        'Get-FabricWorkspaceDatasetRefreshes',
        'Get-FabricWorkspaceUsageMetricsData',
        'Get-FabricWorkspaceUsers',
        'Get-SHA256',
        'New-FabricWorkspaceUsageMetricsReport',
        'Resume-FabricCapacity',
        'Suspend-FabricCapacity',
        'Remove-FabricWorkspace',
        'Invoke-FabricDatasetRefresh'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = @()

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = @(
        'Set-PowerBIWorkspaceToCapacity',
        'Set-PowerBIGroupToCapacity',
        'Set-FabGroupToCapacity',
        'Set-FabWorkspaceToCapacity',
        'Set-FabricGroupToCapacity',
        'Get-PowerBIUsagemetricsQuery',
        'Get-PowerBIWorkspaceUsageMetrics',
        'Get-FabWorkspaceUsageMetrics',
        'Get-FabWorkspaceDatasetRefreshes',
        'Get-FabWorkspaceUsers',
        'Get-FabCapacity',
        'Get-FabCapacityRefreshables',
        'Get-FabCapacityState',
        'Get-FabCapacityTenantOverides',
        'Get-FabCapacityWorkload',
        'Get-FabDatasetRefreshes',
        'Get-FabTenantSettings',
        'Get-FabUsagemetricsQuery',
        'Get-SHA256',
        'New-PowerBIWorkspaceUsageMetrics',
        'New-FabWorkspaceUsageMetrics',
        'Resume-FabCapacity',
        'Suspend-FabCapacity',
        'Login-Fabric',
        'Get-FabWorkspace',
        'Get-FabReport',
        'Add-FabGroupUser',
        'Remove-FabGroupUser',
        'Get-FabGroup',
        'New-FabGroup',
        'New-FabWorkspace',
        'Get-FabricWorkspace',
        'Get-FabDataset',
        'Get-FabricDataset',
        'Get-FabricReport',
        'Add-FabricGroupUser',
        'Remove-FabricGroupUser',
        'Get-FabricGroup',
        'Logout-Fabric',
        'New-FabricGroup',
        'New-FabricWorkspace',
        'Get-FabricCapacity',
        'Remove-FabricGroup',
        'Remove-FabGroup',
        'Remove-FabWorkspace',
        'Remove-PowerBIWorkspace',
        'Remove-PowerBIGroup',
        'Invoke-PowerBIDatasetRefresh',
        'Invoke-FabDatasetRefresh',
        'Get-AllFabCapacities'
    )

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            # Tags = @()

            # A URL to the license for this module.
            LicenseUri = 'https://www.github.com/jojobit/Fabtools/LICENSE.md'

            # A URL to the main website for this project.
            ProjectUri = 'https://www.github.com/jojobit/Fabtools'

            # A URL to an icon representing this module.
            IconUri = 'https://raw.githubusercontent.com/Jojobit/Fabtools/main/Fabtools.ico'

            # ReleaseNotes of this module
            ReleaseNotes = @('Verision 0.6.0:
            - Added Get-AllFabricCapacities function to get all capacities in a tenant.
            - Added invoke-FabricDatasetRefresh function to refresh a dataset.
            - changed the main functions to be with the Fabric prefix instead of Fab, and added Fab as aliases.
            - added IconUri to the manifest.


            '
            )

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}

